<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Weekly Report - {{ $period }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1a2847; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #D4AF37; padding-bottom: 15px; }
        .header h1 { color: #1a2847; margin: 0; font-size: 24px; }
        .header p { color: #6783c1; margin: 5px 0 0; }
        .stats { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .stat-box { background: #f0f3f9; padding: 15px; border-radius: 8px; text-align: center; width: 30%; }
        .stat-box .value { font-size: 22px; font-weight: bold; color: #D4AF37; }
        .stat-box .label { color: #6783c1; font-size: 10px; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #1a2847; color: white; padding: 10px 12px; text-align: left; font-size: 10px; text-transform: uppercase; }
        td { padding: 8px 12px; border-bottom: 1px solid #d9e0f0; }
        tr:nth-child(even) { background: #f8f9fc; }
        .footer { margin-top: 30px; text-align: center; color: #8da2d1; font-size: 10px; border-top: 1px solid #d9e0f0; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>CIMS Weekly Report</h1>
        <p>{{ $period }}</p>
    </div>

    <table>
        <tr>
            <td style="width:33%; text-align:center; background:#f0f3f9; border-radius:8px; padding:20px;">
                <div style="font-size:28px; font-weight:bold; color:#D4AF37;">{{ $totalOrders }}</div>
                <div style="color:#6783c1; font-size:10px; text-transform:uppercase;">Total Orders</div>
            </td>
            <td style="width:33%; text-align:center; background:#f0f3f9; border-radius:8px; padding:20px;">
                <div style="font-size:28px; font-weight:bold; color:#10b981;">{{ $deliveredOrders }}</div>
                <div style="color:#6783c1; font-size:10px; text-transform:uppercase;">Delivered</div>
            </td>
            <td style="width:33%; text-align:center; background:#f0f3f9; border-radius:8px; padding:20px;">
                <div style="font-size:28px; font-weight:bold; color:#D4AF37;">Rp {{ number_format($revenue, 0, ',', '.') }}</div>
                <div style="color:#6783c1; font-size:10px; text-transform:uppercase;">Revenue</div>
            </td>
        </tr>
    </table>

    <h3 style="margin-top:30px; color:#1a2847;">Top Performing Channels</h3>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Company</th>
                <th>Score</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach($topChannels as $i => $ch)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $ch->company_name }}</td>
                <td style="font-weight:bold; color:#D4AF37;">{{ $ch->performance_score }}</td>
                <td style="text-transform:uppercase;">{{ $ch->channel_grade }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by CIMS on {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
